//
// Created by brent on 10/02/2022.
//

#ifndef SONEL_MAPPING_CUDASCENESETTINGS_H
#define SONEL_MAPPING_CUDASCENESETTINGS_H

#define DIFFUSE_BOUNCE_PROB 0.425f
#define SPECULAR_BOUNCE_PROD 0.425f
#define SCALE 0.05f

#endif //SONEL_MAPPING_CUDASCENESETTINGS_H
