//
// Created by brent on 10/02/2022.
//

#ifndef SONEL_MAPPING_CUDASCENESETTINGS_H
#define SONEL_MAPPING_CUDASCENESETTINGS_H

#define DIFFUSE_BOUNCE_PROB 0.9f
#define SPECULAR_BOUNCE_PROD 0.0f
#define SCALE 1.0f

#endif //SONEL_MAPPING_CUDASCENESETTINGS_H
